# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4568cd1474f5db37149c0233f0987e46a9268d2ee89da12c69c82df0982c80109457e45cffa6ef7ab0d0a42cab4aa322367a66f85f38ebc6d3c945b85abf54d8

test:
  secret_key_base: acc14338ae5ea13e8936945e2516578cec78768e443de96c0083dea682e75071e2bede975b606e2e598d012bd8b84fd9ca0006fe8249ac79bdf00abfecef87a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
